# Generated by Django 4.2.21 on 2025-05-14 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10)),
                ('long_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='term_end',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='term_start',
        ),
        migrations.AddField(
            model_name='candidate',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vote.term'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.district'),
        ),
    ]
