# Generated by Django 4.2.21 on 2025-05-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_remove_candidate_age_remove_user_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='term_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='term_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
